<!DOCTYPE HTML>
<HTML LANG=``PT-BR``>
<HEAD>
<META CHARSET=``UTF-8``>
<TITLE>MODASMR </TITLE>
<LINKREL=``STYLESHEET``HREF=``STYLE.CSS``>
</HEAD>
<BODY>
<HEADER>
<H1>MODASMR</H1>
<p> AS MRLHORES ROUPAS VOCE ENCONTRA AQUI</p>
</HEADER>
<SECTION CLASS=``INSTAGRAM``>
<IMG SRC=``INSTAGRAM.PNG``
ALT=``INSTAGRAM``>
<P>@MODASMR</P>
</SECTION>
<SECTION CLASS=``GOVERNO``>
<H2>GOVERNO DO ESTADO</H2>
<IMG SRC=``SAO PAULO.PNG``
ALT=``GOVERNO SP``>
      <P>AQUI VOCE ENCONTRA SEUS ESTUDOS</P>
<SECTION>
<FOOTER>
   <P> C 2026-SITE DESENVOLVIDO PARA AULA DE TI</P>
                                     </FOOTER>
</BODY>
</HTMML>
